name: bmicalculator
description: A new Flutter application.

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.12.0
  url_launcher: 6.0.2
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  get: ^4.1.4
  get_storage: ^2.0.2
  persian_number_utility: ^0.3.2
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"



flutter:

  uses-material-design: true

  assets:
      - assets/icon/icon.png

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Medium.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf


